source 'https://rubygems.org'
gem 'rails', '3.2.1'
gem 'mysql2'
gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'mail'
gem "will_paginate", "~> 3.0.pre2"

#wget http://swftools.org/swftools-0.9.1.tar.gz
#tar -zvxf swftools-0.9.1.tar.gz
#cd swftools-0.9.1
#sudo LDFLAGS="-L/usr/local/lib" CPPFLAGS="-I/usr/local/include" ./configure
#sudo make
#sudo make install

gem 'paperclip'
gem 'aws-ses'
gem 'rubyzip'
gem 'roo'
gem 'RedCloth', :require => 'redcloth'
gem 'httparty'
gem 'fastercsv'
gem 'delayed_job_active_record'
gem 'delayed_job'
gem 'rvideo'
gem 'fileutils'
gem 'mime-types'
gem 'cancan'
gem 'google_visualr'
gem 'daemons'
gem 'prototype-rails'
